brazilian_ecom:
  outputs:
    dev:
      dbname: postgres
      host: de_psql
      pass: admin123
      port: 5432
      schema: analysis
      threads: 1
      type: postgres
      user: admin
  target: dev
